version: '3'

services:
  node:
    image: ritualnetwork/infernet-node:latest
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
      - node-logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
    depends_on:
      - redis
    restart:
      on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stop_grace_period: 1m

  allora-head:
    image: ghcr.io/allora-network/allora-inference-base_head:latest
    platform: linux/amd64
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - network
    restart:
      on-failure
    stop_grace_period: 1m
    volumes:
      - type: bind
        source: ../testkeys/ident1/
        target: /data/keys
        read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [
      "--port", "9527", 
      "--peer-db", "/tmp/peerdb", 
      "--function-db", "/tmp/func-db", 
      "--role", "head", 
      "--rest-api", ":8081",
      "--private-key",              "/data/keys/priv.bin",
    ]

  allora-worker:
    image: ghcr.io/allora-network/allora-inference-base_worker:latest
    platform: linux/amd64
    networks:
      - network
    restart:
      on-failure
    depends_on:
      - allora-head
    stop_grace_period: 1m
    user: 0:0
    volumes:
      - type: bind
        source: ../testkeys/ident2/
        target: /data/keys
        read_only: true
    command: [ 
      "--port",                     "9527", 
      "--peer-db",                  "/tmp/peerdb", 
      "--function-db",              "/tmp/func-db", 
      "--role",                     "worker", 
      "--runtime-path",             "/app/runtime", 
      "--runtime-cli",              "bls-runtime", 
      "--private-key",              "/data/keys/priv.bin",
      "--boot-nodes",               "/dns4/allora-head/tcp/9527/p2p/12D3KooWH9GerdSEroL2nqjpd2GuE5dwmqNi7uHX7FoywBdKcP4q",
    ]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    restart:
      on-failure

  fluentbit:
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"

    environment:
      - FLUENTBIT_CONFIG_PATH=/fluent-bit/etc/fluent-bit.conf
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log:ro
    networks:
      - network
    restart:
      on-failure

networks:
  network:

volumes:
  node-logs:
  redis-data:
